// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ozb3Y13riqPu0l1NNPJCXSC5_ok4PLk',
    appId: '1:645162960578:web:5d35f096cbd2ae7ae91d5b',
    messagingSenderId: '645162960578',
    projectId: 'shuffl-c2c6b',
    authDomain: 'shuffl-c2c6b.firebaseapp.com',
    storageBucket: 'shuffl-c2c6b.appspot.com',
    measurementId: 'G-GG4X8LMNHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSanV7LQeFZR3mz_vbAx-Kdcnzw6ZbiY',
    appId: '1:645162960578:android:b238c4c9e5cd2601e91d5b',
    messagingSenderId: '645162960578',
    projectId: 'shuffl-c2c6b',
    storageBucket: 'shuffl-c2c6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLH3v8teyXzkYXyfm7I0cJHY63kkxBUCk',
    appId: '1:645162960578:ios:d8841e684b98e766e91d5b',
    messagingSenderId: '645162960578',
    projectId: 'shuffl-c2c6b',
    storageBucket: 'shuffl-c2c6b.appspot.com',
    iosBundleId: 'com.shufflmobility.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLH3v8teyXzkYXyfm7I0cJHY63kkxBUCk',
    appId: '1:645162960578:ios:d8841e684b98e766e91d5b',
    messagingSenderId: '645162960578',
    projectId: 'shuffl-c2c6b',
    storageBucket: 'shuffl-c2c6b.appspot.com',
    iosBundleId: 'com.shufflmobility.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ozb3Y13riqPu0l1NNPJCXSC5_ok4PLk',
    appId: '1:645162960578:web:91dd9386b14a1821e91d5b',
    messagingSenderId: '645162960578',
    projectId: 'shuffl-c2c6b',
    authDomain: 'shuffl-c2c6b.firebaseapp.com',
    storageBucket: 'shuffl-c2c6b.appspot.com',
    measurementId: 'G-83NJD4649S',
  );
}
